Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	23	profile_hybrid_init_energies
	11	unzip_chrom_file
	35
Select jobs to execute...

[Mon May  3 21:59:51 2021]
rule profile_hybrid_init_energies:
    input: rawdata/hg19/chr15.fa
    output: output/chr15.hybrid_init.bedgraph
    jobid: 43
    wildcards: chrom_name=chr15

[Mon May  3 21:59:51 2021]
Error in rule profile_hybrid_init_energies:
    jobid: 43
    output: output/chr15.hybrid_init.bedgraph

RuleException:
URLError in line 52 of /home/ethan/Documents/github/hybrid_energy/snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/ethan/Documents/github/hybrid_energy/\n    scripts/profile_hybrid_energies.py\n    '>
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/home/ethan/Documents/github/hybrid_energy/snakefile", line 52, in __rule_profile_hybrid_init_energies
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ethan/Documents/github/hybrid_energy/.snakemake/log/2021-05-03T215951.406889.snakemake.log
